
import EnumValue = require('dw/value/EnumValue')
import MarkupText = require('dw/content/MarkupText');
import MediaFile = require('dw/content/MediaFile');

// autogeneratedfile - 'c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml'
declare global {
    module ICustomAttributes {

		interface Order {
			/**
			* Afterpay Payment Method

				Determines if this is an Afterpay order
			* @group Afterpay - Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#5) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#23)
			*/
			apIsAfterpayOrder: boolean | null;

			/**
			* CashAppPay Payment Method

				Determines if this is an CashAppPay order
			* @group CashAppPay - Cash App Pay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#12) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#27)
			*/
			isCashAppPayOrder: boolean | null;

		}
		interface OrganizationPreferences {
			/**
			* flowIPAddresses
			* @group Afterpay IP Addresses - Afterpay IP Addresses
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#34) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#44)
			*/
			flowIPAddresses: string | null;

		}
		interface PaymentTransaction {
			/**
			* Afterpay Authorise Status

				Afterpay Authorise Status
			* @group Afterpay - Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#51) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#143)
			*/
			apAuthoriseStatus: string | null;

			/**
			* Afterpay Direct Payment Status

				Afterpay Direct Payment Status
			* @group Afterpay - Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#59) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#145)
			*/
			apDirectPaymentStatus: string | null;

			/**
			* Afterpay Initial Status

				Afterpay Initial Status
			* @group Afterpay - Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#67) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#146)
			*/
			apInitialStatus: string | null;

			/**
			* Afterpay Order ID

				Afterpay Order ID
			* @group Afterpay - Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#75) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#141)
			*/
			apPaymentID: string | null;

			/**
			* Afterpay Payment Mode

				Afterpay Payment Mode
			* @group Afterpay - Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#83) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#144)
			*/
			apPaymentMode: string | null;

			/**
			* Afterpay Refund ID
			* @group Afterpay - Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#91) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#147)
			*/
			apRefundID: string | null;

			/**
			* Afterpay Refund Request ID

				RequestId used for latest refund call (basically a timestamp of the call)
			* @group Afterpay - Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#98) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#148)
			*/
			apRefundRequestId: string | null;

			/**
			* Afterpay Token

				Afterpay Token
			* @group Afterpay - Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#106) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#142)
			*/
			apToken: string | null;

			/**
			* Country used for Afterpay payment

				Country used for Afterpay payment
			* 
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#114) 
			*/
			apCountryCode: string | null;

			/**
			* Afterpay Express Checkout

				Afterpay Express Checkout
			* @group Afterpay - Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#122) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#149)
			*/
			apExpressCheckout: boolean | null;

			/**
			* Afterpay Express Checkout Capture Checksum

				Afterpay Express Checkout Capture Checksum
			* @group Afterpay - Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#129) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#150)
			*/
			apExpressCheckoutChecksum: string | null;

		}
		interface SitePreferences {
			/**
			* Brand settings

				Afterpay/Clearpay Brand related settings
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#157) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#319)
			*/
			apBrandSettings: string | null;

			/**
			* CapturePaymentTimeout

				Set timeout for Afterpay capture payments
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#164) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#327)
			*/
			apCaptureTimeout: number | null;

			/**
			* Default Controller Cartridge Name (SiteGenesis Only)

				Name of default storefront controller cartridge
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#171) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#325)
			*/
			apControllerCartridgeName: string | null;

			/**
			* Default Core Cartridge (SiteGenesis Only)
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#180) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#326)
			*/
			apCoreCartridge: string | null;

			/**
			* apDelayRetry

				Time given to delay the Payment retry
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#187) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#328)
			*/
			apDelayRetry: number | null;

			/**
			* Afterpay Display Product Details Page Information

				Determines if the Afterpay information is display on the product details page
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#194) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#321)
			*/
			apDisplayPdpInfo: boolean | null;

			/**
			* Afterpay Display Cart Page Information

				Determines if the Afterpay information is display on the cart page
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#202) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#323)
			*/
			apDisplayCartInfo: boolean | null;

			/**
			* Afterpay Display Product List Page Information

				Determines if the Afterpay information is display on the product tile
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#210) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#322)
			*/
			apDisplayPlpInfo: boolean | null;

			/**
			* Afterpay Payment Mode
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#218) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#324)
			*/
			apPaymentMode: EnumValue<'AUTHORISE' | 'DIRECT_CAPTURE' | null> 

			/**
			* Enable Afterpay
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#234) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#317)
			*/
			enableAfterpay: boolean | null;

			/**
			* Enable Cash App Pay
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#240) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#318)
			*/
			enableCashAppPay: boolean | null;

			/**
			* Enable Express Checkout
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#246) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#329)
			*/
			apEnableExpressCheckout: boolean | null;

			/**
			* Express Checkout Shipping Strategy
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#252) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#330)
			*/
			apExpressCheckoutShippingStrategy: EnumValue<'integrated' | 'deferred' | null> 

			/**
			* Enable BuyNow (Express Checkout with Integrated Shipping Only)
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#268) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#331)
			*/
			apEnableExpressCheckoutBuyNow: boolean | null;

			/**
			* Description that Express Checkout will use for the In-Store Pickup
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#275) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#332)
			*/
			apStorePickupDescription: string | null;

			/**
			* Enable Express Checkout option on product details

				Enable Express Checkout option on product details page.
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#283) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#333)
			*/
			apEnableExpressCheckoutPdp: boolean | null;

			/**
			* Enable Express Checkout option on cart

				Enable Express Checkout option on cart and minicart(SFRA) page.
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#291) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#334)
			*/
			apEnableExpressCheckoutCart: boolean | null;

			/**
			* Restricted Products

				Restricted product ids separated by ","
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#299) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#335)
			*/
			apRestrictedProducts: string | null;

			/**
			* Afterpay JavaScript URL
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#306) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#320)
			*/
			apJavaScript: string | null;

		}
	}
}

declare global {
	interface IGetCustomPreferenceValue {
					/**
			* Brand settings

				Afterpay/Clearpay Brand related settings
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#157) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#319)
			*/
			(name: 'apBrandSettings'): string | null;
			
			/**
			* CapturePaymentTimeout

				Set timeout for Afterpay capture payments
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#164) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#327)
			*/
			(name: 'apCaptureTimeout'): number | null;
			
			/**
			* Default Controller Cartridge Name (SiteGenesis Only)

				Name of default storefront controller cartridge
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#171) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#325)
			*/
			(name: 'apControllerCartridgeName'): string | null;
			
			/**
			* Default Core Cartridge (SiteGenesis Only)
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#180) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#326)
			*/
			(name: 'apCoreCartridge'): string | null;
			
			/**
			* apDelayRetry

				Time given to delay the Payment retry
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#187) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#328)
			*/
			(name: 'apDelayRetry'): number | null;
			
			/**
			* Afterpay Display Product Details Page Information

				Determines if the Afterpay information is display on the product details page
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#194) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#321)
			*/
			(name: 'apDisplayPdpInfo'): boolean | null;
			
			/**
			* Afterpay Display Cart Page Information

				Determines if the Afterpay information is display on the cart page
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#202) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#323)
			*/
			(name: 'apDisplayCartInfo'): boolean | null;
			
			/**
			* Afterpay Display Product List Page Information

				Determines if the Afterpay information is display on the product tile
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#210) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#322)
			*/
			(name: 'apDisplayPlpInfo'): boolean | null;
			
			/**
			* Afterpay Payment Mode
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#218) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#324)
			*/
			(name: 'apPaymentMode'): EnumValue<'AUTHORISE' | 'DIRECT_CAPTURE' | null> 
			
			/**
			* Enable Afterpay
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#234) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#317)
			*/
			(name: 'enableAfterpay'): boolean | null;
			
			/**
			* Enable Cash App Pay
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#240) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#318)
			*/
			(name: 'enableCashAppPay'): boolean | null;
			
			/**
			* Enable Express Checkout
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#246) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#329)
			*/
			(name: 'apEnableExpressCheckout'): boolean | null;
			
			/**
			* Express Checkout Shipping Strategy
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#252) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#330)
			*/
			(name: 'apExpressCheckoutShippingStrategy'): EnumValue<'integrated' | 'deferred' | null> 
			
			/**
			* Enable BuyNow (Express Checkout with Integrated Shipping Only)
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#268) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#331)
			*/
			(name: 'apEnableExpressCheckoutBuyNow'): boolean | null;
			
			/**
			* Description that Express Checkout will use for the In-Store Pickup
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#275) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#332)
			*/
			(name: 'apStorePickupDescription'): string | null;
			
			/**
			* Enable Express Checkout option on product details

				Enable Express Checkout option on product details page.
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#283) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#333)
			*/
			(name: 'apEnableExpressCheckoutPdp'): boolean | null;
			
			/**
			* Enable Express Checkout option on cart

				Enable Express Checkout option on cart and minicart(SFRA) page.
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#291) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#334)
			*/
			(name: 'apEnableExpressCheckoutCart'): boolean | null;
			
			/**
			* Restricted Products

				Restricted product ids separated by ","
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#299) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#335)
			*/
			(name: 'apRestrictedProducts'): string | null;
			
			/**
			* Afterpay JavaScript URL
			* @group Integration_Afterpay - Integration Afterpay
			* @source [attribute](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#306) | [group](file:c:\SFCC\hum\afterpay\afterpay-salesforce-commerce-cloud-main\metadata\afterpay-meta-import\meta\system-objecttype-extensions.xml#320)
			*/
			(name: 'apJavaScript'): string | null;
			
	}
}